### ISSUE TITLE
Namespace AppIndicator3 not available; Installed from tarball 

### ISSUE THREAD

**Issue by neoromantique** [yktoo/indicator-sound-switcher#65]
```
$ indicator-sound-switcher
Traceback (most recent call last):
  File "/usr/local/bin/indicator-sound-switcher", line 35, in <module>
    require_version('AppIndicator3', '0.1')
  File "/usr/lib64/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by neoromantique** [comment]
I'm on Devuan Linux (Same software versions as debian sid)

**Comment by neoromantique** [comment]
I was missing two deps:
```libappindicator3-1
gir1.2-appindicator3-0.1```

Installing them fixes the issue
